package lk.fat2fit.Fat2Fit.Entity.Enum;

public enum FitnessGoal {
    FAT_BURNING,
    CARDIO_TRAINING,
    MUSCLE_STRENGTHENING,
    ENDURANCE_DEVELOPING,
    MUSCLE_GAIN,
    SLIM_FIT_TRAINING,
    SKILL_DEVELOPING,
    BMI_MAINTAINING,
    PHYSICAL_FITNESS,
    OTHERS
}
