# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/fat2fit_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Colombo
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Logging
logging.level.lk.fat2fit=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Tomcat specific - increase limits to match Spring limits
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-part-count=50